# Generated by Django 5.0.3 on 2024-03-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=9)),
                ('crossesPlayer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crosses_players', to='tictactoe.player')),
                ('noughtsPlayer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noughts_players', to='tictactoe.player')),
            ],
        ),
    ]
