# Generated by Django 5.0.3 on 2024-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_rename_name_player_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='handle',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
