# Generated by Django 5.0.3 on 2024-03-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_alter_player_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(default='', max_length=9),
        ),
    ]
