# Generated by Django 5.0.3 on 2024-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0005_rename_status_board_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.CharField(default='         ', max_length=9),
        ),
    ]
