# Generated by Django 5.0.3 on 2024-03-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0006_alter_board_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='crossesPlayer',
            new_name='crosses_player',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='noughtsPlayer',
            new_name='noughts_player',
        ),
    ]
